#!kivy 1.5

<LightFader>:
    flash: flash

    subpad: 40

    Push:
        id: flash
        size_hint: None, None
        size: 34, 34
        main_color: root.color
        text: 'flash'
        center_x: root.center_x
        on_press:
            root.old_value = root.value
            root.value = root.max
            print str(root.old_value) + " / " + str(root.value_normalized)
        on_release:
            root.value = root.old_value
